env:
  browser: true
  es2021: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
  - "plugin:react/recommended"
  - "plugin:cypress/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'cypress'
rules:
  "eol-last":
    - error
    - always
  "react/react-in-jsx-scope": "off"
  "react/prop-types": "off"
  "react-hooks/exhaustive-deps": "off"
  "@typescript-eslint/no-namespace": "off"
ignorePatterns: ["dist/*"]