printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'avoid'
endOfLine: 'lf'
overrides:
  - files: '*.scss'
    options:
      tabWidth: 4
  - files: '*.html'
    options:
      tabWidth: 4
